// Recruiter-style question bank for the on-device guide's intent matcher.
// Used by Classifier.test.ts. Each row is [question, kind, ...acceptableTargetIds].
//
// kind:
//   'nav'  -> navigational/topical: the site is DESIGNED to answer this. Pass iff routed into an acceptable target.
//   'soft' -> conversational/behavioral: no perfect section. Pass iff routed into an acceptable target (best effort).
//   'oos'  -> out of scope (logistics, the recruiter's own company): the site cannot answer.
//             Pass iff NO MATCH or low confidence (score < 0.5). A confident match is a "leak".
//
// Note: this exercises the KEYWORD path (the matcher's fallback, which also answers every
// visitor's first question before the semantic model finishes loading). The semantic path is
// the primary matcher in the browser and is expected to handle the paraphrase/word-form misses.
export type Kind = 'nav' | 'soft' | 'oos';
export type QuestionRow = [string, Kind, ...Array<string>];

export const QUESTION_BANK: Array<QuestionRow> = [
	// ---------------- FLAGSHIP / best work ----------------
	['what is your best work', 'nav', 'flagship'],
	['show me your best work', 'nav', 'flagship'],
	['what is the best thing you have built', 'nav', 'flagship'],
	['what are you most proud of building', 'nav', 'flagship'],
	['whats your most impressive project', 'nav', 'flagship'],
	['show me your strongest work', 'nav', 'flagship'],
	['what is your standout project', 'nav', 'flagship'],
	['what is your flagship project', 'nav', 'flagship'],
	['what is the biggest project you have worked on', 'nav', 'flagship'],
	['show me something impressive', 'nav', 'flagship'],
	['what is the most impressive thing you have made', 'nav', 'flagship'],
	['what is your proudest work', 'nav', 'flagship'],
	['whats the most impressive thing you have built', 'nav', 'flagship'],
	['show me your top project', 'nav', 'flagship'],
	['what is the best project in your portfolio', 'nav', 'flagship', 'projects'],
	['what work are you most proud of', 'nav', 'flagship'],
	['show me your design platform', 'nav', 'flagship'],
	['tell me about your react three js app', 'nav', 'flagship'],
	['what is the full stack platform you built', 'nav', 'flagship'],
	['the design tool you made', 'nav', 'flagship'],
	['what should i look at first', 'soft', 'flagship', 'projects'],
	['what is the highlight of your portfolio', 'soft', 'flagship', 'projects'],
	['biggest project', 'nav', 'flagship'],
	['best project', 'nav', 'flagship'],
	['most impressive work', 'nav', 'flagship'],

	// ---------------- PROJECTS (general) ----------------
	['show me your work', 'nav', 'projects'],
	['show me your projects', 'nav', 'projects'],
	['what have you built', 'nav', 'projects'],
	['what has he built', 'nav', 'projects'],
	['show me your portfolio', 'nav', 'projects'],
	['can i see your case studies', 'nav', 'projects'],
	['what projects have you done', 'nav', 'projects'],
	['see his work', 'nav', 'projects'],
	['portfolio', 'nav', 'projects'],
	['projects', 'nav', 'projects'],
	['what kind of projects do you build', 'nav', 'projects', 'robotics'],
	['show me what you have made', 'nav', 'projects'],
	['walk me through your projects', 'nav', 'projects'],
	['what are some things you have worked on', 'nav', 'projects'],

	// ---------------- ROBOTICS (general) ----------------
	['robotics', 'nav', 'robotics'],
	['robots', 'nav', 'robotics'],
	['show me robots', 'nav', 'robotics'],
	['tell me about your robotics work', 'nav', 'robotics'],
	['what robotics have you done', 'nav', 'robotics'],
	['your hardware work', 'nav', 'robotics'],
	['show me your hardware projects', 'nav', 'robotics', 'projects'],
	['do you build robots', 'nav', 'robotics'],
	['robot work', 'nav', 'robotics'],
	['hardware', 'nav', 'robotics'],
	['what robots have you made', 'nav', 'robotics'],
	['robotics and hardware', 'nav', 'robotics'],
	['show me your robotics projects', 'nav', 'robotics', 'projects'],
	['are you into robotics', 'nav', 'robotics'],

	// ---------------- ROBOT ARM ----------------
	['robot arm', 'nav', 'robot-arm'],
	['tell me about the robot arm', 'nav', 'robot-arm'],
	['the manipulator project', 'nav', 'robot-arm'],
	['franka panda arm', 'nav', 'robot-arm'],
	['collaborative robot', 'nav', 'robot-arm'],
	['robot interaction work', 'nav', 'robot-arm'],
	['c++ ros robot', 'nav', 'robot-arm'],
	['how did you control a robot', 'nav', 'robot-arm'],
	['low level robot control', 'nav', 'robot-arm'],
	['research robot arm', 'nav', 'robot-arm', 'research'],
	['the panda arm project', 'nav', 'robot-arm'],

	// ---------------- SIM ----------------
	['simulation', 'nav', 'sim'],
	['robotics simulation', 'nav', 'sim'],
	['tell me about the robot simulation', 'nav', 'sim'],
	['the 3d animation project', 'nav', 'sim'],
	['animated robot', 'nav', 'sim'],
	['blender work', 'nav', 'sim'],
	['3d modeling project', 'nav', 'sim'],
	['the animated robotics study', 'nav', 'sim', 'robotics'],
	['simulation for a study', 'nav', 'sim'],
	['your blender animation', 'nav', 'sim'],

	// ---------------- AUTONOMOUS ROBOT ----------------
	['autonomous robot', 'nav', 'autonomous'],
	['the robot you built from scratch', 'nav', 'autonomous'],
	['hardware robot', 'nav', 'autonomous'],
	['arduino robot', 'nav', 'autonomous'],
	['did you build a robot', 'nav', 'autonomous', 'robotics'],
	['physical robot', 'nav', 'autonomous'],
	['companion robot', 'nav', 'autonomous'],
	['embedded robot', 'nav', 'autonomous'],
	['the robot he made', 'nav', 'autonomous'],
	['robot for a human robot interaction study', 'nav', 'autonomous', 'research'],

	// ---------------- NOSE KNOWS ----------------
	['nose knows', 'nav', 'noseknows'],
	['tell me about nose knows', 'nav', 'noseknows'],
	['the air quality robot', 'nav', 'noseknows'],
	['the gas sensor project', 'nav', 'noseknows'],
	['electronic nose', 'nav', 'noseknows'],
	['the sneezing robot', 'nav', 'noseknows'],
	['the smell robot', 'nav', 'noseknows'],
	['olfaction project', 'nav', 'noseknows'],
	['the bme688 project', 'nav', 'noseknows'],
	['design competition robot', 'nav', 'noseknows'],
	['the hri conference robot', 'nav', 'noseknows'],
	['air sensor robot', 'nav', 'noseknows'],
	['the robot that sneezes', 'nav', 'noseknows'],
	['hri 2026 project', 'nav', 'noseknows'],

	// ---------------- BLIMP ----------------
	['blimp', 'nav', 'blimp'],
	['tell me about the blimp', 'nav', 'blimp'],
	['the blimp program', 'nav', 'blimp'],
	['flapping wing robot', 'nav', 'blimp'],
	['lighter than air robot', 'nav', 'blimp'],
	['the airship project', 'nav', 'blimp'],
	['bio inspired robot', 'nav', 'blimp'],
	['the mechatronics program', 'nav', 'blimp'],
	['jack the flapper', 'nav', 'blimp'],
	['flapping robot', 'nav', 'blimp'],
	['the mix program', 'nav', 'blimp'],
	['gmu mechatronics', 'nav', 'blimp'],

	// ---------------- PURDUE ----------------
	['purdue', 'nav', 'purdue'],
	['tell me about purdue', 'nav', 'purdue'],
	['the cognition study', 'nav', 'purdue', 'research'],
	['attention study', 'nav', 'purdue', 'research'],
	['the psychology research', 'nav', 'purdue', 'research'],
	['practice effects poster', 'nav', 'purdue'],
	['lexical decision study', 'nav', 'purdue'],
	['undergraduate research', 'nav', 'purdue'],
	['spatial attention research', 'nav', 'purdue', 'research'],
	['your first author poster', 'nav', 'purdue'],

	// ---------------- LIT REVIEW ----------------
	['literature review', 'nav', 'litreview'],
	['systematic review', 'nav', 'litreview'],
	['the review paper', 'nav', 'litreview'],
	['meta analysis', 'nav', 'litreview'],
	['transparency research', 'nav', 'litreview', 'research'],
	['human agent interaction review', 'nav', 'litreview', 'research'],
	['survey paper', 'nav', 'litreview'],
	['your in progress research', 'nav', 'litreview', 'research'],

	// ---------------- AXLE ----------------
	['axle', 'nav', 'axle'],
	['tell me about axle', 'nav', 'axle'],
	['the voice harness', 'nav', 'axle'],
	['your coding agent tool', 'nav', 'axle'],
	['the ai assistant you built', 'nav', 'axle'],
	['your ai project', 'nav', 'axle'],
	['open source project', 'nav', 'axle'],
	['your ai work', 'nav', 'axle'],
	['the agent tool', 'nav', 'axle'],
	['voice tool for coding agents', 'nav', 'axle'],

	// ---------------- SKILLS ----------------
	['skills', 'nav', 'skills'],
	['what are your skills', 'nav', 'skills'],
	['what is your tech stack', 'nav', 'skills'],
	['what technologies do you use', 'nav', 'skills'],
	['what programming languages do you know', 'nav', 'skills'],
	['what languages do you code in', 'nav', 'skills'],
	['what frameworks do you use', 'nav', 'skills'],
	['what tools do you use', 'nav', 'skills'],
	['what can you do', 'nav', 'skills'],
	['what are your technical skills', 'nav', 'skills'],
	['what is your expertise', 'nav', 'skills'],
	['what are your capabilities', 'nav', 'skills'],
	['tech stack', 'nav', 'skills'],
	['programming languages', 'nav', 'skills'],
	['what do you use day to day', 'nav', 'skills'],
	['are you good with python', 'soft', 'skills'],
	['do you know react', 'soft', 'skills'],
	['what are you best at technically', 'soft', 'skills'],
	['what is your strongest language', 'soft', 'skills'],
	['what technical tools do you reach for', 'nav', 'skills'],

	// ---------------- EXPERIENCE ----------------
	['experience', 'nav', 'experience'],
	['what is your experience', 'nav', 'experience'],
	['what is your work history', 'nav', 'experience'],
	['where have you worked', 'nav', 'experience'],
	['tell me about your career', 'nav', 'experience'],
	['can i see your resume', 'nav', 'experience'],
	['can i see your cv', 'nav', 'experience'],
	['what jobs have you had', 'nav', 'experience'],
	['your employment history', 'nav', 'experience'],
	['walk me through your timeline', 'nav', 'experience'],
	['what is your background professionally', 'nav', 'experience', 'bio'],
	['how many years of experience do you have', 'soft', 'experience'],
	['what was your last job', 'nav', 'experience'],
	['what companies have you worked for', 'nav', 'experience'],

	// ---------------- RESEARCH ----------------
	['research', 'nav', 'research'],
	['tell me about your research', 'nav', 'research'],
	['what research have you done', 'nav', 'research'],
	['your hri work', 'nav', 'research'],
	['human robot interaction research', 'nav', 'research'],
	['what studies have you run', 'nav', 'research'],
	['your academic work', 'nav', 'research'],
	['are you a researcher', 'nav', 'research'],
	['tell me about trust and transparency research', 'nav', 'research', 'litreview'],
	['your lab work', 'nav', 'research'],
	['do you have publications', 'nav', 'research'],
	['lead researcher experience', 'nav', 'research', 'experience'],
	['what is your research focus', 'nav', 'research'],

	// ---------------- EDUCATION ----------------
	['education', 'nav', 'education'],
	['what is your education', 'nav', 'education'],
	['what degree do you have', 'nav', 'education'],
	['where did you go to school', 'nav', 'education'],
	['what university did you attend', 'nav', 'education'],
	['do you have a masters', 'nav', 'education'],
	['what did you study', 'nav', 'education'],
	['your academic background', 'nav', 'education'],
	['where did you study', 'nav', 'education'],
	['tell me about your graduate program', 'nav', 'education'],
	['what school did you go to', 'nav', 'education'],
	['are you in grad school', 'nav', 'education'],

	// ---------------- OPS / MANUFACTURING ----------------
	['manufacturing', 'nav', 'ops'],
	['operations', 'nav', 'ops'],
	['your manufacturing background', 'nav', 'ops'],
	['tell me about your operations experience', 'nav', 'ops', 'experience'],
	['factory work', 'nav', 'ops'],
	['cad experience', 'nav', 'ops', 'experience'],
	['cnc work', 'nav', 'ops'],
	['process improvement', 'nav', 'ops'],
	['workflow efficiency work', 'nav', 'ops'],
	['ergonomics work', 'nav', 'ops'],
	['did you work in a factory', 'nav', 'ops'],

	// ---------------- CONTACT / HIRE ----------------
	['contact', 'nav', 'contact'],
	['how do i contact you', 'nav', 'contact'],
	['how can i reach you', 'nav', 'contact'],
	['how do i get in touch', 'nav', 'contact'],
	['can i hire you', 'nav', 'contact'],
	['i want to hire you', 'nav', 'contact'],
	['whats your email', 'nav', 'contact'],
	['email', 'nav', 'contact'],
	['linkedin', 'nav', 'contact'],
	['whats your linkedin', 'nav', 'contact'],
	['how do i reach out', 'nav', 'contact'],
	['can we connect', 'nav', 'contact'],
	['i want to work with you', 'nav', 'contact'],
	['how do i message you', 'nav', 'contact'],
	['lets talk', 'soft', 'contact'],
	['get in touch', 'nav', 'contact'],
	['reach out', 'nav', 'contact'],
	['hire him', 'nav', 'contact'],
	['talk to him', 'nav', 'contact'],

	// ---------------- TEAM / COLLABORATION / LEADERSHIP ----------------
	['are you a team player', 'nav', 'team'],
	['how are you on a team', 'nav', 'team'],
	['how do you work with others', 'nav', 'team'],
	['tell me about your collaboration style', 'nav', 'team'],
	['how do you communicate', 'nav', 'team'],
	['whats your work ethic', 'nav', 'team'],
	['what is your personality like', 'nav', 'team'],
	['what are you like to work with', 'nav', 'team'],
	['do you have leadership experience', 'nav', 'team'],
	['how are you socially', 'nav', 'team'],
	['are you good with people', 'nav', 'team'],
	['how do you handle teamwork', 'nav', 'team'],
	['tell me about your soft skills', 'nav', 'team'],
	['how do you work on a team', 'nav', 'team'],
	['can you lead a team', 'nav', 'team'],
	['how do you communicate with teammates', 'nav', 'team'],
	['are you a good collaborator', 'nav', 'team'],
	['how do you deal with conflict', 'soft', 'team'],
	['tell me about a time you led a team', 'soft', 'team'],
	['how do you give feedback', 'soft', 'team'],

	// ---------------- MAKER / HOBBIES ----------------
	['hobbies', 'nav', 'maker'],
	['what are your hobbies', 'nav', 'maker'],
	['what do you build for fun', 'nav', 'maker'],
	['what do you do for fun', 'nav', 'maker'],
	['do you have side projects', 'nav', 'maker'],
	['tell me about your side projects', 'nav', 'maker'],
	['do you do 3d printing', 'nav', 'maker'],
	['do you build speakers', 'nav', 'maker'],
	['do you do woodworking', 'nav', 'maker'],
	['do you have a homelab', 'nav', 'maker'],
	['what do you tinker with', 'nav', 'maker'],
	['what do you do off the clock', 'nav', 'maker'],
	['what do you make in your free time', 'nav', 'maker'],
	['what do you do outside of work', 'soft', 'maker'],
	['do you build things for fun', 'nav', 'maker'],
	['what are you into outside of work', 'soft', 'maker'],
	['any fun side projects', 'nav', 'maker'],
	['what do you do in your spare time', 'soft', 'maker'],

	// ---------------- BIO / ABOUT / STORY ----------------
	['tell me about yourself', 'nav', 'bio'],
	['who are you', 'nav', 'bio'],
	['tell me about him', 'nav', 'bio'],
	['whats your background', 'nav', 'bio'],
	['introduce yourself', 'nav', 'bio'],
	['whats your story', 'nav', 'bio'],
	['who is jacob', 'nav', 'bio'],
	['tell me about jacob', 'nav', 'bio'],
	['give me a bio', 'nav', 'bio'],
	['how do you approach problems', 'nav', 'bio', 'team'],
	['what are you about', 'soft', 'bio'],
	['walk me through your background', 'nav', 'bio', 'experience'],
	['describe yourself', 'soft', 'bio'],
	['who am i talking to', 'soft', 'bio'],

	// ---------------- MOTIVATION / VALUES (soft) ----------------
	['what motivates you', 'soft', 'bio', 'team'],
	['what drives you', 'soft', 'bio', 'team'],
	['what are you passionate about', 'soft', 'bio', 'robotics', 'research'],
	['what gets you excited', 'soft', 'bio'],
	['what do you care about', 'soft', 'bio'],
	['what are your values', 'soft', 'bio', 'team'],
	['why do you do what you do', 'soft', 'bio'],
	['what is your why', 'soft', 'bio'],
	['what energizes you at work', 'soft', 'bio', 'team'],
	['what kind of problems do you like solving', 'soft', 'bio', 'skills'],
	['what is most important to you in a job', 'soft', 'bio', 'team'],
	['what makes you tick', 'soft', 'bio'],

	// ---------------- BEHAVIORAL / STAR (soft) ----------------
	['tell me about a time you failed', 'soft', 'bio', 'team', 'experience'],
	['tell me about a challenge you overcame', 'soft', 'bio', 'team', 'experience'],
	['describe a difficult problem you solved', 'soft', 'skills', 'experience', 'bio'],
	['tell me about a conflict with a coworker', 'soft', 'team'],
	['give me an example of leadership', 'soft', 'team'],
	['tell me about a time you went above and beyond', 'soft', 'team', 'experience'],
	['describe a time you missed a deadline', 'soft', 'experience', 'team'],
	['tell me about a mistake you made', 'soft', 'bio', 'team'],
	['how have you handled pressure', 'soft', 'team', 'bio'],
	['tell me about a time you disagreed with your boss', 'soft', 'team'],
	['describe a project that did not go well', 'soft', 'projects', 'experience'],
	['tell me about a time you took initiative', 'soft', 'team', 'experience'],
	['give an example of problem solving', 'soft', 'skills', 'bio'],
	['tell me about working under a tight deadline', 'soft', 'team', 'experience'],

	// ---------------- STRENGTHS / WEAKNESSES (soft) ----------------
	['what are your strengths', 'soft', 'skills', 'team', 'bio'],
	['what is your greatest strength', 'soft', 'skills', 'team', 'bio'],
	['what are your weaknesses', 'soft', 'bio', 'team'],
	['what is your biggest weakness', 'soft', 'bio', 'team'],
	['what could you improve on', 'soft', 'bio', 'team'],
	['what do you struggle with', 'soft', 'bio', 'team'],
	['what makes you a good fit', 'soft', 'skills', 'team', 'bio'],
	['why should we hire you', 'soft', 'skills', 'flagship', 'contact'],
	['what sets you apart', 'soft', 'flagship', 'skills', 'bio'],
	['what is your superpower', 'soft', 'skills', 'bio'],

	// ---------------- CAREER GOALS / FUTURE (soft) ----------------
	['what are your career goals', 'soft', 'bio', 'experience'],
	['where do you see yourself in five years', 'soft', 'bio'],
	['what do you want to do next', 'soft', 'bio', 'experience'],
	['what are you looking for in your next role', 'soft', 'bio'],
	['what kind of role do you want', 'soft', 'bio', 'experience'],
	['what are your ambitions', 'soft', 'bio'],
	['what do you want to learn', 'soft', 'skills', 'bio'],
	['where do you want to grow', 'soft', 'bio', 'skills'],
	['what is your dream job', 'soft', 'bio'],
	['what are you hoping to get out of this role', 'soft', 'bio'],

	// ---------------- WHY (mostly oos) ----------------
	['why this company', 'oos'],
	['why do you want to work here', 'oos'],
	['why are you interested in us', 'oos'],
	['what do you know about our company', 'oos'],
	['why this role', 'oos'],
	['why are you leaving your current job', 'oos'],
	['why are you looking right now', 'oos'],
	['what attracted you to this position', 'oos'],

	// ---------------- LOGISTICS (oos) ----------------
	['what are your salary expectations', 'oos'],
	['what is your expected salary', 'oos'],
	['how much do you want to make', 'oos'],
	['what is your current compensation', 'oos'],
	['are you willing to relocate', 'oos'],
	['where are you located', 'oos'],
	['can you work remotely', 'oos'],
	['do you want remote or hybrid', 'oos'],
	['when can you start', 'oos'],
	['what is your availability', 'oos'],
	['what is your notice period', 'oos'],
	['what is your work authorization status', 'oos'],
	['do you need visa sponsorship', 'oos'],
	['are you authorized to work in the us', 'oos'],
	['are you interviewing elsewhere', 'oos'],
	['whats your timeline', 'oos'],
	['are you open to contract work', 'oos'],
	['what days can you work', 'oos'],

	// ---------------- CURVEBALLS (soft) ----------------
	['what is something you changed your mind about', 'soft', 'bio'],
	['what are you learning right now', 'soft', 'skills', 'bio', 'maker'],
	['what is a hot take you have', 'soft', 'bio'],
	['if you werent doing this what would you do', 'soft', 'bio', 'maker'],
	['whats something not on your resume', 'soft', 'bio', 'maker'],
	['what is a problem you cant stop thinking about', 'soft', 'bio', 'research'],
	['tell me a fun fact about you', 'soft', 'bio', 'maker'],
	['what book are you reading', 'soft', 'bio', 'maker'],
	['what would your friends say about you', 'soft', 'bio', 'team'],
	['what makes you different', 'soft', 'bio', 'flagship'],

	// ---------------- MORE FLAGSHIP ----------------
	['what is the coolest thing you built', 'nav', 'flagship'],
	['show me your best project', 'nav', 'flagship'],
	['what are you proudest of', 'nav', 'flagship'],
	['whats your strongest piece of work', 'nav', 'flagship'],
	['what is the most impressive project', 'nav', 'flagship'],
	['show me the standout work', 'nav', 'flagship'],
	['whats the best thing in your portfolio', 'nav', 'flagship', 'projects'],
	['your most impressive build', 'nav', 'flagship'],

	// ---------------- MORE PROJECTS ----------------
	['what else have you built', 'nav', 'projects'],
	['show me more work', 'nav', 'projects'],
	['what projects are you working on', 'nav', 'projects'],
	['give me a tour of your work', 'nav', 'projects'],
	['can i see your projects', 'nav', 'projects'],
	['what have you shipped', 'nav', 'projects'],
	['show me everything', 'soft', 'projects'],
	['what are your main projects', 'nav', 'projects'],

	// ---------------- MORE ROBOTICS / SPECIFIC ----------------
	['what robots have you built', 'nav', 'robotics'],
	['show me your robot projects', 'nav', 'robotics', 'projects'],
	['are you a robotics engineer', 'nav', 'robotics'],
	['do you do robotics', 'nav', 'robotics'],
	['tell me about your robots', 'nav', 'robotics'],
	['the ros project', 'nav', 'robot-arm'],
	['robot control software', 'nav', 'robot-arm'],
	['the blender simulation', 'nav', 'sim'],
	['robot you made from scratch', 'nav', 'autonomous'],
	['the sneezing air quality robot', 'nav', 'noseknows'],
	['robot that detects smells', 'nav', 'noseknows'],
	['the flapping blimp', 'nav', 'blimp'],
	['bio inspired airship', 'nav', 'blimp'],
	['your psychology study', 'nav', 'purdue', 'research'],
	['the attention and practice study', 'nav', 'purdue'],
	['the transparency literature review', 'nav', 'litreview', 'research'],
	['your voice coding tool', 'nav', 'axle'],
	['the open source voice harness', 'nav', 'axle'],

	// ---------------- MORE SKILLS (specific tech) ----------------
	['do you know typescript', 'soft', 'skills'],
	['are you comfortable with c++', 'soft', 'skills'],
	['do you have experience with ros', 'soft', 'skills', 'robot-arm'],
	['do you use git', 'soft', 'skills'],
	['are you frontend or backend', 'soft', 'skills'],
	['do you do machine learning', 'soft', 'skills', 'research'],
	['whats your favorite language', 'soft', 'skills'],
	['how good is your javascript', 'soft', 'skills'],
	['do you know three js', 'soft', 'skills', 'flagship'],
	['are you a full stack developer', 'soft', 'skills'],
	['do you write tests', 'soft', 'skills'],
	['do you know docker', 'soft', 'skills'],
	['do you have cloud experience', 'soft', 'skills'],
	['do you know aws', 'soft', 'skills'],
	['do you do embedded programming', 'soft', 'skills', 'robotics'],
	['are you good at cad', 'soft', 'skills', 'ops'],
	['what is your strongest skill', 'soft', 'skills'],
	['what are your technical strengths', 'soft', 'skills'],

	// ---------------- MORE EXPERIENCE ----------------
	['how long have you been working', 'soft', 'experience'],
	['what was your most recent role', 'nav', 'experience'],
	['tell me about your previous jobs', 'nav', 'experience'],
	['what roles have you held', 'nav', 'experience'],
	['summarize your experience', 'nav', 'experience'],
	['what is your professional history', 'nav', 'experience'],
	['what have you done professionally', 'nav', 'experience', 'bio'],

	// ---------------- MORE RESEARCH ----------------
	['what papers have you written', 'nav', 'research', 'litreview'],
	['tell me about your hri research', 'nav', 'research'],
	['what is your research about', 'nav', 'research'],
	['do you publish papers', 'nav', 'research'],
	['what academic work have you done', 'nav', 'research'],
	['are you in a research lab', 'nav', 'research'],
	['what are you researching', 'nav', 'research'],

	// ---------------- MORE EDUCATION ----------------
	['what is your major', 'nav', 'education'],
	['did you graduate', 'nav', 'education'],
	['what is your gpa', 'soft', 'education'],
	['are you a student', 'nav', 'education'],
	['when did you graduate', 'nav', 'education'],
	['what is your degree in', 'nav', 'education'],

	// ---------------- MORE CONTACT ----------------
	['how do i apply', 'soft', 'contact'],
	['can i schedule a call', 'soft', 'contact'],
	['whats the best way to reach you', 'nav', 'contact'],
	['i would like to hire you', 'nav', 'contact'],
	['how can i connect with you', 'nav', 'contact'],
	['where can i find you online', 'soft', 'contact'],

	// ---------------- MORE TEAM / BEHAVIORAL ----------------
	['how do you handle disagreements', 'soft', 'team'],
	['are you easy to work with', 'nav', 'team'],
	['how do you mentor others', 'soft', 'team'],
	['describe your communication style', 'nav', 'team'],
	['how do you collaborate', 'nav', 'team'],
	['can you work independently', 'soft', 'team', 'bio'],
	['how do you handle criticism', 'soft', 'team', 'bio'],
	['are you a leader or a follower', 'soft', 'team'],
	['how do you build trust on a team', 'soft', 'team'],
	['tell me about your leadership style', 'nav', 'team'],

	// ---------------- MORE MAKER ----------------
	['what do you build at home', 'nav', 'maker'],
	['do you make things for fun', 'nav', 'maker'],
	['whats your latest side project', 'nav', 'maker'],
	['do you 3d print', 'nav', 'maker'],
	['tell me about your homelab', 'nav', 'maker'],
	['do you build audio gear', 'nav', 'maker', 'skills'],
	['what do you do on weekends', 'soft', 'maker'],
	['do you do any woodworking', 'nav', 'maker'],

	// ---------------- MORE BIO ----------------
	['give me the elevator pitch', 'soft', 'bio'],
	['summarize who you are', 'nav', 'bio'],
	['tell me your story', 'nav', 'bio'],
	['what is your background', 'nav', 'bio', 'experience'],
	['what should i know about you', 'soft', 'bio'],
	['paint me a picture of who you are', 'soft', 'bio'],

	// ---------------- MORE LOGISTICS (oos) ----------------
	['do you have references', 'oos'],
	['can you pass a background check', 'oos'],
	['what is your desired start date', 'oos'],
	['are you a us citizen', 'oos'],
	['how soon can you join', 'oos'],
	['what is your current title', 'oos'],
	['do you have a drivers license', 'oos'],
	['are you vaccinated', 'oos'],

	// ---------------- MORE CURVEBALLS (soft) ----------------
	['whats your favorite project of all time', 'soft', 'flagship', 'projects'],
	['if you could build anything what would it be', 'soft', 'bio', 'maker'],
	['what excites you about technology', 'soft', 'bio', 'skills'],
	['what is the best advice you have received', 'soft', 'bio'],
	['who is your role model', 'soft', 'bio'],
	['what would you do with a free weekend', 'soft', 'maker', 'bio'],
	['describe your ideal work day', 'soft', 'bio', 'team'],
	['whats a skill you wish you had', 'soft', 'skills', 'bio'],

	// ---------------- ADDITIONAL ----------------
	['show me your engineering work', 'nav', 'projects', 'robotics'],
	['what is your favorite thing you built', 'soft', 'flagship', 'projects'],
	['do you have a github', 'nav', 'contact', 'axle'],
	['whats your proudest moment', 'soft', 'flagship', 'bio'],
	['what hardware have you designed', 'nav', 'robotics', 'projects'],
	['tell me about your embedded work', 'nav', 'robotics', 'autonomous'],
	['have you worked with sensors', 'soft', 'noseknows', 'robotics'],
	['do you have conference experience', 'soft', 'research', 'noseknows', 'experience'],
	['what conferences have you presented at', 'soft', 'research', 'noseknows'],
	['are you published', 'nav', 'research'],
	['what is your design background', 'soft', 'flagship', 'skills'],
	['do you know how to weld', 'soft', 'ops', 'maker'],
	['have you done any teaching', 'soft', 'team', 'research'],
	['what programming languages are you fluent in', 'nav', 'skills'],
	['tell me about your most recent project', 'nav', 'projects', 'flagship'],
	['what are you working on these days', 'soft', 'projects', 'litreview'],
	['do you have startup experience', 'soft', 'experience'],
	['what is your management experience', 'soft', 'team', 'experience'],
	['how do you stay organized', 'soft', 'team', 'bio'],
	['what is your approach to learning', 'soft', 'bio', 'skills'],
	['are you detail oriented', 'soft', 'team', 'bio'],
	['how do you prioritize work', 'soft', 'team', 'bio'],
	['what motivates you to build things', 'soft', 'bio', 'maker'],
	['describe your work style', 'soft', 'team', 'bio'],
	['what kind of engineer are you', 'soft', 'skills', 'bio', 'robotics'],
	['what makes you excited to come to work', 'soft', 'bio', 'team'],
];

// A small set of queries that must ALWAYS route exactly as stated. Unlike the
// statistical bank above, every one of these is a hard guarantee.
export const CANONICAL: Array<[string, string]> = [
	['show me his best work', 'flagship'],
	['show me his most impressive work', 'flagship'],
	['robotics', 'robotics'],
	['show me his robotics and hardware projects', 'robotics'],
	['what is his tech stack', 'skills'],
	['tell me about his research', 'research'],
	['how do I contact him', 'contact'],
	['nose knows', 'noseknows'],
	['blimp', 'blimp'],
	['robot arm', 'robot-arm'],
	['simulation', 'sim'],
	['autonomous robot', 'autonomous'],
	['axle', 'axle'],
	['literature review', 'litreview'],
	['purdue', 'purdue'],
	['education', 'education'],
	['experience', 'experience'],
	['manufacturing', 'ops'],
	['is he a team player', 'team'],
	['hobbies', 'maker'],
	['tell me about him', 'bio'],
	['projects', 'projects'],
	['jack the flapper', 'blimp'],
	['the panda arm project', 'robot-arm'],
	['bio inspired robot', 'blimp'],
	['what can you do', 'skills'],
];
